version: '3.7'

services:

  orderer:
    image: hyperledger/fabric-orderer:2.5
    container_name: orderer.example.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISPROFILE=SampleDevModeSolo
    working_dir: /var/hyperledger/orderer
    command: orderer
    volumes:
      - ./data/orderer:/var/hyperledger/orderer
    ports:
      - "7050:7050"
    networks:
      - local

  peer:
    image: hyperledger/fabric-peer:2.5
    container_name: peer0.org1.example.com
    environment:
      - CORE_PEER_ID=peer0.org1.example.com
      - CORE_PEER_ADDRESS=peer0.org1.example.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1.example.com:7052
      - CORE_PEER_LOCALMSPID=Org1MSP
    working_dir: /var/hyperledger/peer
    command: peer node start
    volumes:
      - ./data/peer:/var/hyperledger/peer
    ports:
      - "7051:7051"
      - "7052:7052"
    networks:
      - local

  ca:
    image: hyperledger/fabric-ca:1.5
    container_name: ca.org1.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org1
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./data/ca:/etc/hyperledger/fabric-ca-server
    networks:
      - local

networks:
  local:
    name: ${NETWORK_NAME}